### ISSUE TITLE
confirming url download source of TEST.CLIP_ORI_PATH 

### ISSUE THREAD

**Issue by nancywang1991** [wengzejia1/Open-VCLIP#13]
Hi there, I'm having trouble getting the test script to run and I was wondering if it could be due to the wrong source for the original CLIP model path? I downloaded it from https://openaipublic.azureedge.net/clip/models/b8cca3fd41ae0c99ba7e8951adf17d267cdb84cd88be6f7c2e0eca1737a03836/ViT-L-14.pt from OpenAI. Is this correct? 

The error that I'm getting is this:

`RuntimeError: Detected that you are using FX to torch.jit.trace a dynamo-optimized function. This is not supported at the moment.`

Copying parts of the traceback in case it is helpful:

`Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/ivnet/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 68, in _wrap
    fn(i, *args)
  File "/home/ubuntu/Open-VCLIP/slowfast/utils/multiprocessing.py", line 60, in run
    ret = func(cfg)
  File "/home/ubuntu/Open-VCLIP/tools/test_net.py", line 374, in test
    flops, params = misc.log_model_info(
  File "/home/ubuntu/Open-VCLIP/slowfast/utils/misc.py", line 189, in log_model_info
    flops = get_model_stats(model, cfg, "flop", use_train_input)
  File "/home/ubuntu/Open-VCLIP/slowfast/utils/misc.py", line 168, in get_model_stats
    count_dict, *_ = model_stats_fun(model, inputs)
  File "/home/ubuntu/anaconda3/envs/ivnet/lib/python3.8/site-packages/fvcore/nn/flop_count.py", line 147, in flop_count
    for op, flop in flop_counter.by_operator().items():
  File "/home/ubuntu/anaconda3/envs/ivnet/lib/python3.8/site-packages/fvcore/nn/jit_analysis.py", line 265, in by_operator
    stats = self._analyze()
`

**Comment by wengzejia1** [comment]
The error seems to be associated with the "log_model_info" function, located in the line 374 of the 'test_net.py' file. Maybe you can try to set LOG_MODEL_INFO as 'False' to skip the function call and assess if the issue persists.

**Comment by nancywang1991** [comment]
Thanks! I tried it but I'm still getting the same error. I'm copying the whole error traceback in case you see anything. I'm still suspecting that maybe my CLIP model that I downloaded has some issues. Can you please point me to where you downloaded the model file for the original CLIP? Thanks again!

`Traceback` (most recent call last):
  File "tools/run_net.py", line 56, in <module>
    main()
  File "tools/run_net.py", line 41, in main   
    launch_job(cfg=cfg, init_method=args.init_method, func=test)
  File "/home/ubuntu/Open-VCLIP/slowfast/utils/misc.py", line 415, in launch_job
    torch.multiprocessing.spawn(
  File "/home/ubuntu/anaconda3/envs/ivnet/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 241, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method="spawn")
  File "/home/ubuntu/anaconda3/envs/ivnet/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 197, in start_processes
    while not context.join():
  File "/home/ubuntu/anaconda3/envs/ivnet/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 158, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/ivnet/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 68, in _wrap
    fn(i, *args)
  File "/home/ubuntu/Open-VCLIP/slowfast/utils/multiprocessing.py", line 60, in run
    ret = func(cfg)
  File "/home/ubuntu/Open-VCLIP/tools/test_net.py", line 379, in test
    misc.log_model_info(model, cfg, use_train_input=False)
  File "/home/ubuntu/Open-VCLIP/slowfast/utils/misc.py", line 189, in log_model_info
    flops = get_model_stats(model, cfg, "flop", use_train_input)
  File "/home/ubuntu/Open-VCLIP/slowfast/utils/misc.py", line 168, in get_model_stats
    count_dict, *_ = model_stats_fun(model, inputs)
  File "/home/ubuntu/anaconda3/envs/ivnet/lib/python3.8/site-packages/fvcore/nn/flop_count.py", line 147, in flop_count
    for op, flop in flop_counter.by_operator().items():
  File "/home/ubuntu/anaconda3/envs/ivnet/lib/python3.8/site-packages/fvcore/nn/jit_analysis.py", line 265, in by_operator
    stats = self._analyze()
  File "/home/ubuntu/anaconda3/envs/ivnet/lib/python3.8/site-packages/fvcore/nn/jit_analysis.py", line 551, in _analyze
    graph = _get_scoped_trace_graph(self._model, self._inputs, self._aliases)
  File "/home/ubuntu/anaconda3/envs/ivnet/lib/python3.8/site-packages/fvcore/nn/jit_analysis.py", line 176, in _get_scoped_trace_graph
    graph, _ = _get_trace_graph(module, inputs)
  File "/home/ubuntu/anaconda3/envs/ivnet/lib/python3.8/site-packages/torch/jit/_trace.py", line 1296, in _get_trace_graph
    outs = ONNXTracedModule(
  File "/home/ubuntu/anaconda3/envs/ivnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)   
  File "/home/ubuntu/anaconda3/envs/ivnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/ivnet/lib/python3.8/site-packages/torch/jit/_trace.py", line 138, in forward
    graph, out = torch._C._create_graph_by_tracing(
  File "/home/ubuntu/anaconda3/envs/ivnet/lib/python3.8/site-packages/torch/jit/_trace.py", line 129, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/home/ubuntu/anaconda3/envs/ivnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)   
  File "/home/ubuntu/anaconda3/envs/ivnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1561, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/ivnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _slow_forward
    result = self.forward(*input, **kwargs)   
  File "/home/ubuntu/Open-VCLIP/slowfast/models/temporalclip_video_model.py", line 209, in forward
    img_encode = self.model.encode_image(x)   
  File "/home/ubuntu/Open-VCLIP/slowfast/models/temporalclip_video_model.py", line 438, in encode_image
    return self.visual(image.type(self.dtype))
  File "/home/ubuntu/anaconda3/envs/ivnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)   
  File "/home/ubuntu/anaconda3/envs/ivnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1561, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/ivnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _slow_forward
    result = self.forward(*input, **kwargs)   
  File "/home/ubuntu/Open-VCLIP/slowfast/models/customize_visiontransformer.py", line 536, in forward
    x = self.transformer(x)
  File "/home/ubuntu/anaconda3/envs/ivnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)   
  File "/home/ubuntu/anaconda3/envs/ivnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1561, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/ivnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _slow_forward
    result = self.forward(*input, **kwargs)   
  File "/home/ubuntu/Open-VCLIP/slowfast/models/customize_visiontransformer.py", line 496, in forward
    return checkpoint_sequential(self.resblocks, 3, x)
  File "/home/ubuntu/anaconda3/envs/ivnet/lib/python3.8/site-packages/torch/utils/checkpoint.py", line 575, in checkpoint_sequential
    input = checkpoint(
  File "/home/ubuntu/anaconda3/envs/ivnet/lib/python3.8/site-packages/torch/_compile.py", line 24, in inner
    return torch._dynamo.disable(fn, recursive)(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/ivnet/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 470, in _fn
    raise RuntimeError(
RuntimeError: Detected that you are using FX to torch.jit.trace a dynamo-optimized function. This is not supported at the moment.

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ubuntu/anaconda3/envs/ivnet/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/ubuntu/anaconda3/envs/ivnet/lib/python3.8/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent) 
_pickle.UnpicklingError: pickle data was truncated
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ubuntu/anaconda3/envs/ivnet/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/ubuntu/anaconda3/envs/ivnet/lib/python3.8/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent) 
_pickle.UnpicklingError: pickle data was truncated
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ubuntu/anaconda3/envs/ivnet/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/ubuntu/anaconda3/envs/ivnet/lib/python3.8/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent) 
_pickle.UnpicklingError: pickle data was truncated`

**Comment by wengzejia1** [comment]
I downloaded the model weights by invoking the `load` function from the `clip.py`  file in the OpenAI CLIP repository(https://github.com/openai/CLIP/blob/main/clip/clip.py).

The download path you provided：
(https://openaipublic.azureedge.net/clip/models/b8cca3fd41ae0c99ba7e8951adf17d267cdb84cd88be6f7c2e0eca1737a03836/ViT-L-14.pt) is correct and is sourced from the aforementioned clip.py file in the original OpenAI repository.
